Добавлены интерфейсы
Adobe-for-Alex/adobe-api pull request #5
Opened 2024-10-28 22:59 UTC by Vladislav8653

Добавлены интерфейсы для понимания работы сервиса. В них ещё могут добавляться методы, но это станет понятнее при реализации

2024-10-29 08:17 UTC, Chamber6821 requested changes

2024-10-29 08:17 UTC, Chamber6821 commented on .idea/.gitignore
`.idea` находится в гитигноре

2024-10-29 08:17 UTC, Chamber6821 commented on Contracts/Board.ts
Весь код должен быть в папке `src`

2024-10-29 08:17 UTC, Chamber6821 commented on Contracts/Board.ts
> +    IsSubscriptionValid () : boolean;
Все методы должны называться camelCase'ом без приставок get, set, is.

Возвращаемое значение лучше делать промисом, потому что везде могут быть потенциальные обращения к другим сервисам или базе данных.

Аргументы должны называться в соответствии с назначением.

2024-10-29 08:40 UTC, Chamber6821 commented
В целом лучше структура будет, если не добавлять в сущности новые методы (их должно быть сильно меньше 5, в идеале 1 метод). Более подходящая структура, но скорее всего не полная:

```ts
interface User {
  id(): Promise<UserId>
  email(): Promise<string>
  password(): Promise<string>
}

interface Users {
  all(): Promise<User[]>
  withId(id: UserId): Promise<User | undefined>
}

interface Board {
  id(): Promise<BoardId>
  users(): Promise<Users>
  attach(user: User): Promise<void>
  detach(user: User): Promise<void>
  freeUserSlots(): Promise<number>
}

interface Boards {
  all(): Promise<Board[]>
  withId(id: BoardId): Promise<Board | undefined>
  forUserWith(id: UserId): Promise<Board | undefined>
  add(...): Promise<Board>
}
```

2024-10-29 15:32 UTC, Chamber6821 commented
Покажи пример, как ты хочешь соединять эти абстракции

[Вот](https://github.com/yegor256/takes?tab=readme-ov-file#exception-handling) что, я имею в виду

2024-10-30 07:53 UTC, Chamber6821 commented
Я опущу использование `await`, что бы не загромождать код. Этот пример - псевдокод (например express здесь используется не правильно)
```ts
const service = new ServiceMemory(
  new CachedBoards(new PrismaBoards(prisma)),
  new CachedUsers(new PrismaUsers(prisma))
)

app.get('/boards', () => service.boards().all())
app.get('/users/{id}', (id) => service.users().withId(id))
app.get('/users/{id}/board', (id) => service.users().withId(id).board())
```

2024-10-30 18:48 UTC, Vladislav8653 commented
я запушил изменения в свой локальный форкнутый репозиторий. Сейчас разберусь, как их добавить в этот пул реквест

2024-10-30 18:56 UTC, Vladislav8653 commented
а они сами тут появляются. К делу

я так понимаю, классы PrismaBoards, PrismaBoard и тд являются репозиториями, то есть предоставляют методы для манипуляции, которые лезут в БД и что-то там делают. В конструктор передается Prisma. Вопрос: где брать модели моих юзеров, бордов в БД? Они пока не существуют или где-то есть? Типа пример: attach юзера к board. Параметр - user. А как его прикрепить к board, где хранится id board?

2024-10-30 18:58 UTC, Vladislav8653 commented
(prisma.board.select(id))

вот пример из твоего кода

prisma это что за класс, что там хранится board? Это же класс не наш, там инструменты для работы с БД.

2024-10-30 19:41 UTC, Chamber6821 commented
`prisma.board.select(id)`:
- `prisma = new PrismaClient()`
- `prisma.user` - сгенеренная штука. Тебе нужено в `schema.prisma` описать табличку и сделать миграцию, тогда у тебя появится аттрибут с соответсвующим именем

Почитай как начать работать с Prisma, там это написано

2024-10-30 19:45 UTC, Chamber6821 commented
`PrismaBoards` и `PrismaBoard` - это не репозитории. Они могут быть похожи на репозитории, но это не так. Они описывают часть взаимодействия между объектами. За этими абстракциями действительно могут стоять репозитории, а могу и не стоять. Не стоит думать о них, как о репозиториях

2024-11-01 08:49 UTC, Vladislav8653 commented
теперь попробовать довести до работоспособного состояния, сделав ендпоинты и попробовать записать/почитать БД?

2024-11-01 10:33 UTC, Chamber6821 commented on .idea/.gitignore
@Vladislav8653

2024-11-01 10:34 UTC, Chamber6821 commented
Нет, это абсолютно не то, что нужно на этом этапе. Вот тебе пример, что от тебя нужно https://github.com/Adobe-for-Alex/telegram-bot/pull/8. К тому же ты не внес предыдущие правки

2024-11-01 12:00 UTC, Vladislav8653 commented
Вопрос:
есть интерфейс:
```ts
export default interface Board {
    users(): Promise<Users>
    attach(user: User): Promise<void>
    detach(user: User): Promise<void>
    freeUserSlots(): Promise<number>
}
```
я хочу привести пример его использования (по аналогии с Германа примерами). Но у меня получается каждый метод просто оберткой для интерфейсного 
```ts
async function getAllBoardUsers(board : Board) : Promise<Users> {
    return await board.users();
}

async function attachUserToBoard(user : User, board : Board) : Promise<void> {
    return board.attach(user);
}

async function detachUserFromBoard(user : User, board : Board) : Promise<void> {
    return board.detach(user);
}

async function getFreeBoardSlots(board : Board) : Promise<number> {
    return board.freeUserSlots();
}
```
У Германа реализована разная логика с помощью интерфейсных методов. Мне приходят в голову только примеры, которые и являются напрямую тем, что "возвращает интерфейс" . Что я делаю не так или какой пример можно придумать для иллюстрации использования методов интерфейса?

2024-11-01 15:20 UTC, Chamber6821 commented
В твоем микросервисе действительно многие сценарии выглядят тривиально, так и должно быть. У Гераман сценарии не тривиальны, но их меньше, а у тебя будет больше по количеству, но каждый сценарий будет меньше. Тебе нужно написать сценарий для каждого (может быть кроме тривиальных, которые дергают 1 метод) хендла твоего REST API.

В примерах, в которых ты прописал ты считаешь, что у тебя уже есть и `user`, и `board`, но на самом деле это не так. Скорее всего тебе через HTTP запрос приходит только их ID. Ты должен из множества объектов (`users`/`boards`) достать нужный тебе объект по ID

2024-11-01 18:40 UTC, Vladislav8653 commented
## Получить всех пользователей на доске
```ts
async function getAllBoardUsers(boardId : string) : Promise<Users> {
    const board = await boards.boardWithId(boardId);
    return await board.users();
}
```

## Прикрепить пользователя к доске
```ts
async function attachUserToBoard(userId : string, boardId : string) : Promise<void> {
    const board = await boards.boardWithId(boardId);
    const user = await users.userWithId(userId);
    return board.attach(user);
}
```

## Открепить пользователя от доски
```ts
async function detachUserFromBoard(userId : string, boardId : string) : Promise<void> {
    const board = await boards.boardWithId(boardId);
    const user = await users.userWithId(userId);
    return board.detach(user);
}
```

## Получить количество свободных мест на доске
```ts
async function getFreeBoardSlots(boardId : string) : Promise<number> {
    const board = await boards.boardWithId(boardId);
    return board.freeUserSlots();
}
```

2024-11-01 19:28 UTC, Chamber6821 commented
Посмотри пожалуйста мои первые правки. Ты их просто проигнорировал, без выполнения их я дальше смотреть код не буду

2024-11-04 08:48 UTC, Vladislav8653 commented
хелло
вопрос: какую правку из начала я не учел? Я хочу точно понять, что мне надо сделать. Спасибо

2024-11-04 11:49 UTC, Chamber6821 commented on .idea/.gitignore
@Vladislav8653

2024-11-04 11:50 UTC, Chamber6821 commented
@Vladislav8653 просмотри все обсуждение с самого начала и каждый не закрытый тред. Там их всего 2 и сейчас еще кину

2024-11-04 11:52 UTC, Chamber6821 requested changes

2024-11-04 11:52 UTC, Chamber6821 commented on package-lock.json
На проект использует PNPM, а не NPM

2024-11-04 11:52 UTC, Chamber6821 commented on prisma/migrations/20241101072318_created_user_and_board_models/migration.sql
Разработка структуры БД не относится к этому PR

2024-11-04 11:52 UTC, Chamber6821 commented on src/examples/boardExamples.ts
Какой-то лишний файл попал в индекс

2024-11-05 15:22 UTC, Vladislav8653 commented
удалена .idea и prisma

2024-11-05 16:56 UTC, Chamber6821 requested changes

2024-11-05 16:56 UTC, Chamber6821 commented on package-lock.json
Удали это нахуй. У нас PNPM используется, что не ясно?

2024-11-05 16:56 UTC, Chamber6821 commented on prisma/schema.prisma
Верни шаблонную пустую схему

2024-11-05 16:56 UTC, Chamber6821 commented on src/examples/boardExamples.ts
Удали этот файл

2024-11-05 20:40 UTC, Vladislav8653 commented
я исправил твои замечания, а в общем что надо еще сделать ?

2024-11-05 20:56 UTC, Chamber6821 requested changes

2024-11-05 20:56 UTC, Chamber6821 commented on prisma/schema.prisma
> -}
Верни как было

2024-11-05 21:29 UTC, Vladislav8653 commented on prisma/schema.prisma
> -}
бля а как было? я понимаю что тебя это заебло, просто если это стоковое содержание файла, то пусть так и будет, нет?

2024-11-05 21:31 UTC, Chamber6821 commented on prisma/schema.prisma
> -}
Так ты его стер блин. Он изначально был в стоковом состоянии после инициализации. Погугли как откатить отдельный файл к конкретному коммиту

2024-11-05 21:56 UTC, Vladislav8653 commented on prisma/schema.prisma
> -}
а, понял, без проблем

2024-11-06 00:04 UTC, Vladislav8653 commented on prisma/schema.prisma
> -}
мда не без проблем. Я вернусь к этому завтра, но если вас не устраивают результаты работы и есть человек, который сделает это issue, то смело отдавайте ему

2024-11-06 10:04 UTC, Vladislav8653 commented
prisma schema теперь в стоковом состоянии, что еще надо?

2024-11-06 18:44 UTC, Chamber6821 requested changes

2024-11-06 18:44 UTC, Chamber6821 commented on .gitignore
> +
`.gitignore` - это общий файл, не стоит в него добавлять вещи специфичные для отдельно взятого разработчика

2024-11-06 18:44 UTC, Chamber6821 commented on prisma/schema.prisma
> +}
Откати это

2024-11-06 18:44 UTC, Chamber6821 commented on src/boards/Boards.ts
> +    boardWithId(id: string): Promise<Board | undefined>
Лучше название `withId` без `board`

2024-11-06 18:44 UTC, Chamber6821 commented on src/boards/Boards.ts
> +    add(board : Board): Promise<Board>
Двоеточие для обозначения типа принято писать вот так: `value: Type`

2024-11-06 18:44 UTC, Chamber6821 commented on src/user/User.ts
> +    id() : Promise<string>
Двоеточие для обозначения типа принято писать вот так: `value: Type`

2024-11-06 18:44 UTC, Chamber6821 commented on src/user/User.ts
> +    email() : Promise<string>
Двоеточие для обозначения типа принято писать вот так: `value: Type`

2024-11-06 18:44 UTC, Chamber6821 commented on src/user/User.ts
> +    password() : Promise<string>
Двоеточие для обозначения типа принято писать вот так: `value: Type`

2024-11-06 18:44 UTC, Chamber6821 commented on src/user/User.ts
> +    board() : Promise<Board | undefined>
Двоеточие для обозначения типа принято писать вот так: `value: Type`

2024-11-06 18:44 UTC, Chamber6821 commented on src/users/Users.ts
> +    all() : Promise<User[]>
Двоеточие для обозначения типа принято писать вот так: `value: Type`

2024-11-06 18:44 UTC, Chamber6821 commented on src/users/Users.ts
> +    userWithId(id : String) : Promise<User | undefined>
Лучше название `withId` без `user`

2024-11-06 18:44 UTC, Chamber6821 commented on src/users/Users.ts
> +    userWithId(id : String) : Promise<User | undefined>
Двоеточие для обозначения типа принято писать вот так: `value: Type`

2024-11-06 19:17 UTC, Vladislav8653 commented
исправил отступы с ":" и откатил схема.призма до состояния старого коммита

2024-11-06 20:43 UTC, Chamber6821 requested changes

2024-11-06 20:43 UTC, Chamber6821 commented on .gitignore
> +
Удали это

2024-11-06 20:46 UTC, Vladislav8653 commented on .gitignore
> +
окей)

2024-11-07 12:39 UTC, Chamber6821 commented
Этот PR закрывается, поскольку разработка интерфейсов передана мне

2024-11-07 12:39 UTC, closed without merging